---
- job:
    name: pep8-test
    parent: base
    description: this is running the unit tests for this project
    run: playbooks/pep8.yaml

- project:
    check:
      jobs:
        - pep8-test:
            nodeset:
              nodes:
                - name: container
                  label: pod-rhel-8

