---

include:
  'openstack-tox-pep8': 'osp-tox-pep8'
  'openstack-tox-py36': 'osp-tox-py36'
  'openstack-tox-py37': 'osp-tox-py37'
  'openstack-tox-py38': 'osp-tox-py38'
  'openstack-tox-py39': 'osp-tox-py39'


exclude:
  /.*/:  # every project
    'osp-17.0':
      'openstack-tox-py36': 'OSP 17 release is not using py38 and lower'
      'openstack-tox-py37': 'OSP 17 release is not using py38 and lower'
      'openstack-tox-py38': 'OSP 17 release is not using py38 and lower'

  'nova':
    'osp-17.0':
      'openstack-tox-py36': 'we do not support this Python version'
      'openstack-tox-py38': 'we do not support this Python version'


add:
  /.*/:  # every project
    'osp-17.0':
      'openstack-tox-py39':
        'voting': false
        'type':
          - 'gate'

  'gnocchi':
    'osp-17.0':
      'openstack-tox-pep8':
        'voting': false
        'type':
          - 'check'
          - 'gate'

  'python-tripleoclient':
    'osp-17.0':
      'openstack-tox-py39':
        'voting': false
        'type':
          - 'check'
          - 'gate'


override: {}  # TODO(sdatko): implement


copy: {}  # TODO(sdatko): implement
