---
#
# Znoyder configuration
#
# This file contains specification of jobs that should be present
# in the generated Zuul configuration. The behaviour is defined
# by a set of top-level directives with a following execution order:
#   include -> exclude -> add -> override -> copy
#
# Each of <project-name> and <release-tag> can be specified as literally
# expected value (string) or as a regular expression. In case of the latter,
# the specifier must start and end with a forward slash: / character.
#
# For example, 'osp-17.0' string as <release-tag> matches only the osp-17.0 tag
# and it is equivalent to setting /^osp-17\.0$/ as a tag specifier.
#


#
# Branches config
#
branches:
  'osp-17.0':
    downstream: '^rhos-17.*$'
    upstream: 'stable/wallaby'


#
# Include map: specify which upstream jobs to collect
#
# Format:
#   '<release-tag>':
#     '<upstream-job-name>': '<downstream-job-name>'
#
include:
  'osp-17.0':
    'openstack-tox-pep8': 'osp-tox-pep8'
    'openstack-tox-py39': 'osp-tox-py39'
    'openstack-tox-functional-py39': 'osp-tox-functional-py39'
    'cinder-tox-functional-py39': 'cinder-tox-functional-py39'
    'nova-tox-functional-py39': 'nova-tox-functional-py39'
    'placement-nova-tox-functional-py39': 'placement-nova-tox-functional-py39'
    # yamllint disable-line rule:line-length
    'glance-tox-functional-py39-cursive-tips': 'glance-tox-functional-py39-cursive-tips'
    # yamllint disable-line rule:line-length
    'glance-tox-functional-py39-rbac-defaults': 'glance-tox-functional-py39-rbac-defaults'
    'openstack-tox-functional': 'osp-tox-functional'


#
# Exclude map: specify which collected jobs to ignore (exception to include)
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': '<reason>'
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37': 'Python 3.7 is not available in our repos'
#
exclude:
  'cinder':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'glance':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'glance_store':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'manila':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'manila-ui':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'python-cinderclient':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'python-cinderlib':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'python-glanceclient':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'python-manilaclient':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'python-os-brick':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'python-swiftclient':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

  'swift':  # OSPCRE-22
    'osp-17.0':
      'osp-tox-pep8': 'Storage DFG decided to opt-out for now'
      'osp-tox-py39': 'Storage DFG decided to opt-out for now'
      'osp-tox-functional-py39': 'Storage DFG decided to opt-out for now'

#
# Add map: specify custom jobs to add in the generated result
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37':
#         'voting': false
#         'type': ['check']
#
add:
  'gnocchi':
    'osp-17.0':
      'osp-tox-pep8':
        type:
          - 'check'
          - 'gate'

  'keystone':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'check'
          - 'gate'

  'openstack-barbican':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'gate'

  'openstack-heat-agents':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'gate'

  'openstack-tripleo-common':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'gate'

  'python-castellan':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'gate'

  'python-keystoneauth1':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'gate'

  'python-keystonemiddleware':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'check'
          - 'gate'

  'python-openstacksdk':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'check'
          - 'gate'

  'python-tripleoclient':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'gate'
        vars:
          rhos_release_args: '17.0'

  'python-zaqarclient':
    'osp-17.0':
      'osp-tox-py39':
        type:
          - 'check'
          - 'gate'
        vars:
          rhos_release_args: '17.0'


#
# Override map: change options of all the jobs collected so far
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37':
#         type: 'check'
#         voting: false
#         required-projects: ~
#
override:
  /.*/:  # every project
    'osp-17.0':
      'osp-tox-pep8':
        voting: true
        required-projects: ~
      'osp-tox-py39':
        voting: true
        required-projects: ~

  'aodh':
    'osp-17.0':
      'osp-tox-py39':
        voting: false  # problem with running mysqld in centos container
        vars:
          rhos_release_args: '17.0'
          tox_envlist: 'py39-mysql'
          tox_environment:
            AODH_TEST_DRIVERS: 'mysql'

  'ceilometer':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'ironic-prometheus-exporter':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'keystone':  # rhbz#2052499
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'nova':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'ovn-octavia-provider':  # rhbz#2069526
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'openstack-designate':  # rhbz#2069553
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'openstack-ec2-api':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'openstack-tripleo-heat-templates':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'os-net-config':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'oslo.messaging':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'oslo.middleware':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'oslo.vmware':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'python-aodhclient':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'python-barbicanclient':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'python-ironicclient':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'python-keystoneclient':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false

  'python-kuryr-lib':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'python-neutron-lib':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false

  'python-neutronclient':  # rhbz#2059099
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false

  'python-openstacksdk':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'python-oslo-config':
    'osp-17.0':
      'osp-tox-py39':
        voting: false

  'python-ovsdbapp':  # rhos release provides the openvswitch package
    'osp-17.0':
      'osp-tox-pep8':
        vars:
          rhos_release_args: '17.0'
      'osp-tox-py39':
        vars:
          rhos_release_args: '17.0'

  'python-proliantutils':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false

  'python-tripleoclient':
    'osp-17.0':
      'osp-tox-pep8':
        vars:
          rhos_release_args: '17.0'
      'osp-tox-py39':
        voting: false  # one test expects to be run as non-root user
        vars:
          rhos_release_args: '17.0'

  'tripleo-ansible':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-tox-py39':
        voting: false


#
# Copy map: duplicate a job entry from one pipeline/project to another
#
copy: {}  # TODO(sdatko): implement
