---
#
# Znoyder configuration
#
# This file contains specification of jobs that should be present
# in the generated Zuul configuration. The behaviour is defined
# by a set of top-level directives with a following execution order:
#   include -> exclude -> add -> override -> copy
#
# Each of <project-name> and <release-tag> can be specified as literally
# expected value (string) or as a regular expression. In case of the latter,
# the specifier must start and end with a forward slash: / character.
#
# For example, 'osp-17.0' string as <release-tag> matches only the osp-17.0 tag
# and it is equivalent to setting /^osp-17\.0$/ as a tag specifier.
#

#
# Include map: specify which upstream jobs to collect
#
# Format:
#   '<upstream-job-name>': '<downstream-job-name>'
#
# TODO(sdatko): implement support for multiple OSP releases
#
include:
  'openstack-tox-pep8': 'osp-tox-pep8'
  'openstack-tox-py36': 'osp-tox-py36'
  'openstack-tox-py37': 'osp-tox-py37'
  'openstack-tox-py38': 'osp-tox-py38'
  'openstack-tox-py39': 'osp-tox-py39'


#
# Exclude map: specify which collected jobs to ignore (exception to include)
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': '<reason>'
# e.g.
#   /.*/:
#     'osp-17.0':
#       'openstack-tox-py37': 'Python 3.7 is not available in our repos'
#
exclude:
  /.*/:  # every project
    'osp-17.0':
      'openstack-tox-py36': 'OSP 17 release is not using py38 and lower'
      'openstack-tox-py37': 'OSP 17 release is not using py38 and lower'
      'openstack-tox-py38': 'OSP 17 release is not using py38 and lower'

  'nova':
    'osp-17.0':
      'openstack-tox-py36': 'we do not support this Python version'
      'openstack-tox-py38': 'we do not support this Python version'


#
# Add map: specify custom jobs to add in the generated result
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'openstack-tox-py37':
#         'voting': false
#         'type': ['check']
#
add:
  'gnocchi':
    'osp-17.0':
      'openstack-tox-pep8':
        type:
          - 'check'
          - 'gate'

  'keystone':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'check'
          - 'gate'

  'openstack-barbican':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'gate'

  'openstack-heat-agents':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'gate'

  'openstack-tripleo-common':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'gate'

  'python-castellan':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'gate'

  'python-keystoneauth1':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'gate'

  'python-keystonemiddleware':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'check'
          - 'gate'

  'python-openstacksdk':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'check'
          - 'gate'

  'python-tripleoclient':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'gate'
        vars:
          rhos_release_args: '17.0'

  'python-zaqarclient':
    'osp-17.0':
      'openstack-tox-py39':
        type:
          - 'check'
          - 'gate'
        vars:
          rhos_release_args: '17.0'


#
# Override map: change options of all the jobs collected so far
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'openstack-tox-py37':
#         type: 'check'
#         voting: false
#         required-projects: ~
#
override:
  /.*/:  # every project
    'osp-17.0':
      'openstack-tox-pep8':
        voting: true
        required-projects: ~
      'openstack-tox-py39':
        voting: true
        required-projects: ~

  'aodh':
    'osp-17.0':
      'openstack-tox-py39':
        vars:
          rhos_release_args: '17.0'
          tox_envlist: 'py39-mysql'
          tox_environment:
            AODH_TEST_DRIVERS: 'mysql'

  'python-ovsdbapp':
    'osp-17.0':
      'openstack-tox-py39':
        vars:
          rhos_release_args: '17.0'

  'python-tripleoclient':
    'osp-17.0':
      'openstack-tox-pep8':
        vars:
          rhos_release_args: '17.0'
      'openstack-tox-py39':
        type: 'check'
        vars:
          rhos_release_args: '17.0'


#
# Copy map: duplicate a job entry from one pipeline/project to another
#
copy: {}  # TODO(sdatko): implement
