---
#
# Znoyder configuration
#
# This file contains specification of jobs that should be present
# in the generated Zuul configuration. The behaviour is defined
# by a set of top-level directives with a following execution order:
#   include -> exclude -> add -> override -> copy
#
# Each of <project-name> and <release-tag> can be specified as literally
# expected value (string) or as a regular expression. In case of the latter,
# the specifier must start and end with a forward slash: / character.
#
# For example, 'osp-17.0' string as <release-tag> matches only the osp-17.0 tag
# and it is equivalent to setting /^osp-17\.0$/ as a tag specifier.
#


#
# Branches config
#
branches:
  'osp-17.0':
    downstream: '^rhos-17.0-trunk-patches$'
    upstream: 'stable/wallaby'


#
# Include map: specify which upstream jobs to collect
#
# Format:
#   '<release-tag>':
#     '<upstream-job-name>': '<downstream-job-name>'
#
include:
  'osp-17.0':
    'openstack-tox-pep8': 'osp-tox-pep8'
    'openstack-tox-py39': 'osp-rpm-py39'
    'openstack-tox-functional-py39': 'osp-tox-functional-py39'
    'cinder-tox-functional-py39': 'cinder-tox-functional-py39'
    'nova-tox-functional-py39': 'nova-tox-functional-py39'
    'placement-nova-tox-functional-py39': 'placement-nova-tox-functional-py39'
    # yamllint disable-line rule:line-length
    'glance-tox-functional-py39-cursive-tips': 'glance-tox-functional-py39-cursive-tips'
    # yamllint disable-line rule:line-length
    'glance-tox-functional-py39-rbac-defaults': 'glance-tox-functional-py39-rbac-defaults'
    'openstack-tox-functional': 'osp-tox-functional'


#
# Exclude map: specify which collected jobs to ignore (exception to include)
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': '<reason>'
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37': 'Python 3.7 is not available in our repos'
#
exclude: {}


#
# Add map: specify custom jobs to add in the generated result
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37':
#         'voting': false
#         'type': ['check']
#
add:
  'gnocchi':
    'osp-17.0':
      'osp-tox-pep8':
        pipeline:
          - 'check'
          - 'gate'

  'keystone':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'check'
          - 'gate'

  'openstack-barbican':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'gate'

  'openstack-tempest':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'check'

  'openstack-heat-agents':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          extra_commands:
            - 'dnf install -y python3-testrepository'
            - 'dnf reinstall -y platform-python-setuptools'
        pipeline:
          - 'gate'

  'openstack-tripleo-common':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'gate'

  'python-castellan':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'gate'

  'python-keystoneauth1':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'gate'

  'python-keystonemiddleware':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'check'
          - 'gate'

  'python-openstacksdk':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'check'
          - 'gate'

  'python-tripleoclient':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'gate'

  'python-zaqarclient':
    'osp-17.0':
      'osp-rpm-py39':
        pipeline:
          - 'check'
          - 'gate'


#
# Override map: change options of all the jobs collected so far
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37':
#         pipeline: 'check'
#         voting: false
#         required-projects: ~
#
override:
  /.*/:  # every project
    'osp-17.0':
      'osp-tox-pep8':
        voting: true
        required-projects: ~
      'osp-rpm-py39':
        voting: false
        required-projects: ~
        vars:
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'aodh':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false  # problem with running mysqld in centos container
        vars:
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
          tox_envlist: 'py39-mysql'
          tox_environment:
            AODH_TEST_DRIVERS: 'mysql'

  'ceilometer':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'ironic':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'ironic-prometheus-exporter':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-rpm-py39':
        voting: false

  'keystone':  # rhbz#2052499
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-rpm-py39':
        voting: false

  'nova':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'openstack-barbican':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'openstack-designate':  # rhbz#2069553
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-rpm-py39':
        voting: false

  'openstack-ec2-api':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'openstack-ironic-python-agent':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'openstack-tripleo-common':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'openstack-tripleo-heat-templates':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-rpm-py39':
        voting: false

  'openstack-tripleo-image-elements':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'os-net-config':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
        voting: false

  'oslo.messaging':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
        voting: false
      'osp-tox-pep8':
        voting: false

  'oslo.middleware':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
        voting: false

  'oslo.service':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'oslo.utils':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'oslo.vmware':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
        voting: false
      'osp-tox-pep8':
        voting: false

  'ovn-octavia-provider':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
        voting: false  # rhbz#2069526
      'osp-tox-pep8':
        voting: false  # rhbz#2069526

  'python-aodhclient':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'python-automaton':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-barbicanclient':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false
        vars:
          extra_commands:
            # yamllint disable-line rule:line-length
            - 'dnf install -y python3-coverage python3-stestr python3-requests-mock openstack-dashboard'
            # yamllint disable-line rule:line-length
            - 'ln -s /usr/share/openstack-dashboard/ /usr/lib/python3.9/site-packages/'

  'python-castellan':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-dracclient':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-heatclient':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-ironic-lib':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-ironicclient':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'python-keystoneclient':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false

  'python-kuryr-lib':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'python-metalsmith':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-neutron-lib':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
      'osp-tox-pep8':
        voting: false

  'python-neutronclient':  # rhbz#2059099
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-rpm-py39':
        voting: false

  'python-octaviaclient':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-openstacksdk':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'python-os-ken':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-oslo-cache':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-oslo-config':
    'osp-17.0':
      'osp-rpm-py39':
        voting: false

  'python-oslo-context':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-oslo-db':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-oslo-policy':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-oslo-privsep':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-oslo-upgradecheck':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-oslo-versionedobjects':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-ovsdbapp':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'
      'osp-tox-pep8':  # rhos release provides the openvswitch package
        vars:
          rhos_release_args: '17.0'

  'python-stevedore':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-sushy':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-sushy-oem-idrac':
    'osp-17.0':
      'osp-rpm-py39':
        vars:
          allow_test_requirements_txt: true
          rhos_release_args: '17.0'
          rhos_release_extra_repos: 'rhelosp-17.0-trunk-brew'

  'python-proliantutils':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false

  'python-tripleoclient':
    'osp-17.0':
      'osp-tox-pep8':
        vars:
          rhos_release_args: '17.0'
      'osp-rpm-py39':
        voting: false  # one test expects to be run as non-root user

  'tripleo-ansible':
    'osp-17.0':
      'osp-tox-pep8':
        voting: false
      'osp-rpm-py39':
        voting: false


#
# Copy map: duplicate a job entry from one pipeline/project to another
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       - '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       - 'osp-tox-py37':
#           from: 'check'
#           to: 'gate'
#           as: 'tox-py37'
#           voting: false
#           required-projects: ~
#
# The `from/to/as` are special keywords in options.
# Everything else is considered as a job parameter to override after copy.
#
# Either `from/to` or `as` is always required (all three are also possible).
#
copy:
  /.*/:  # every project
    /.*/:  # every tag
      - 'osp-tox-pep8':
          from: 'check'
          to: 'weekly'
      - 'osp-rpm-py39':
          from: 'check'
          to: 'weekly'
