---
#
# Znoyder configuration
#
# This file contains specification of jobs that should be present
# in the generated Zuul configuration. The behaviour is defined
# by a set of top-level directives with a following execution order:
#   include -> exclude -> add -> override -> copy
#
# Each of <project-name> and <release-tag> can be specified as literally
# expected value (string) or as a regular expression. In case of the latter,
# the specifier must start and end with a forward slash: / character.
#
# For example, 'osp-17.0' string as <release-tag> matches only the osp-17.0 tag
# and it is equivalent to setting /^osp-17\.0$/ as a tag specifier.
#
# THE VALUES FROM THIS FILE CAN BE OVERWRITTEN BY ENTRIES FROM config.d/ FILES.
#


#
# Branches config: link upstream releases with downstream branches
#
branches: {}


#
# Additional projects to be covered
#
extra_projects: {}


#
# Include map: specify which upstream jobs to collect
#
# Format:
#   '<release-tag>':
#     '<upstream-job-name>': '<downstream-job-name>'
#
include: {}


#
# Exclude map: specify which collected jobs to ignore (exception to include)
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': '<reason>'
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37': 'Python 3.7 is not available in our repos'
#
exclude: {}


#
# Add map: specify custom jobs to add in the generated result
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37':
#         'voting': false
#         'type': ['check']
#
add: {}


#
# Override map: change options of all the jobs collected so far
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       'osp-tox-py37':
#         pipeline: 'check'
#         voting: false
#         required-projects: ~
#
override: {}


#
# Copy map: duplicate a job entry from one pipeline/project to another
#
# Format:
#   '<project-name>':
#     '<release-tag>':
#       - '<job-name>': {<options...>}
# e.g.
#   /.*/:
#     'osp-17.0':
#       - 'osp-tox-py37':
#           from: 'check'
#           to: 'gate'
#           as: 'tox-py37'
#           voting: false
#           required-projects: ~
#
# The `from/to/as` are special keywords in options.
# Everything else is considered as a job parameter to override after copy.
#
# Either `from/to` or `as` is always required (all three are also possible).
#
copy: {}
