name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Packages installation
        run: apk add --no-cache git python3 py3-pip && pip3 install tox
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tox call tests
        run: tox -v

