name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Packages
        run: apk add --no-cache git python3 py3-pip && pip3 install tox
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tox
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          tox -v

