name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: themattrix/tox
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Tests
      run: |
          tox -v
